function GetCredit(songID){
	switch(songID){
	case bgm_forest: return "Forest - Efraim"	
	case bgm_industrial: return "Industrial - Efraim"	
	case bgm_industrialDay: return "Industrial Day - Efraim"	
	case bgm_jazz_kit: return "Jazz Kit - Efraim"	
	case bgm_melanchonyAndAmbiance: return "Melanchony and Ambiance - Efraim"	
	case bgm_PVPUndergroundSuugestion: return "PVP Underground Suggestion - Efraim"	
	case bgm_song2bcutupinloops: return "song2bcutupinloops - Efraim"	
	case bgm_dearRival: return "Dear Rival - Digitalis"	
	case bgm_encounterOfALifetime: return "Encounter of a Lifetime - Digitalis"	
	case bgm_fallingDepression: return "Falling Depression - Digitalis"	
	case bgm_jazzBarTheme: return "Jazz Bar Theme - Digitalis"	
	case bgm_coastal: return "Coastal - Duke Minus the Groove"	
	case bgm_sunsetRide: return "Sunset Ride - Duke Minus the Groove"
	case bgm_amaranthMinigameElevator: return "Amaranth Minigame Elevator - ODAE"
	case bgm_diddleShadowRegion: return "Diddle Shadow Region - ODAE"	
	case bgm_diddle: return "Diddle - ODAE"		
	case bgm_graveyard: return "Graveyard - ODAE"	
	case bgm_makingAChoice: return "Making a Choice - ODAE"	
	case bgm_mapEditorPercussive: return "Map Editor Percussive - ODAE"	
	case bgm_natureWalkCaves: return "Nature Walk Caves - ODAE"	
	case bgm_natureWalk: return "Nature Walk - ODAE"
	case bgm_orchestra: return "Orchestra - ODAE"
	case bgm_pad: return "Pad - ODAE"
	case bgm_plains: return "Plains - ODAE"	
	case bgm_regolith: return "Regolith - ODAE"	
	case bgm_shadowNightSecond: return "Shadow Night Second - ODAE"	
	case bgm_wayOfPebbles: return "Way of Pebbles - AC_Composer"
	case bgm_theIceCaves: return "The Ice Caves - AC_Composer"
	case bgm_snowyRidge: return "Snowy Ridge - AC_Composer"
	case bgm_runeStones: return "Rune Stones - AC_Composer"
	case bgm_storiesOnTheWall: return "Stories on the Wall - AC_Composer"
	case bgm_legendOfTheStone: return "Legen of the Stone - AC_Composer"
	case bgm_theBookOfRocks: return "The Book of Rocks - AC_Composer"
	}
}